FROM oven/bun:1 AS base 
WORKDIR /usr/src/app

# install dep into temp dir
FROM base AS install 
RUN mkdir -p /dtemp/dev 
COPY package.json bun.lock /temp/dev/ 
RUN cd /temp/dev && bun install --fronzen-lockfile

# install with --prod
RUN mkdir -p /temp/prod 
COPY package.json bun.lock /temp/dev 
RUN cd /temp/prod && bun install --frozen-lockfile --production 

# copy node_modules from temp dir
FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node-modules 
COPY . .

# test & build 
ENV NODE_ENV=production 
RUN bun test 
RUN bun run build 

# copy prod dep and source code into final image
FROM base AS release 
COPY --from=install /temp/prod/node_modules node_modules
COPY --from=prerelease /usr/src/app/index.ts .
COPY --from=prerelease /usr/src/app/package.json .

# run the app
USER bun
EXPOSE 3000/tcp
ENTRYPOINT [ "bun", "run", "index.ts" ]